// Tablas de códigos para documentos de exportación (110/111/112).
//
// Fuente: Compendio de Normas Anexo 51 del Servicio Nacional de Aduanas
// (aduana.cl/compendio-de-normas-anexo-51/aduana/2009-11-19/163937.html),
// extraídas el 2026-08-12 — países del 51-9, puertos del 51-11, vías del
// 51-13, cláusulas del 51-21, formas de pago del 51-22, bultos del 51-23,
// unidades del 51-24 y modalidades del 51-26. Las MONEDAS son la excepción:
// no son códigos de Aduana sino el TEXTO literal de la enumeración
// TipMonType del XSD del SII (DTE_v10.xsd), que es lo que <TpoMoneda> exige.
//
// Ver certificacion/exportacion-y-liquidacion.md en la raíz del proyecto.

export interface CodigoAduana {
  value: number
  label: string
}

// <TpoMoneda> — texto literal, NO código (enumeración TipMonType del SII).
export const MONEDAS_EXPORTACION: string[] = [
  "BOLIVAR",
  "BOLIVIANO",
  "CHELIN",
  "CORONA DIN",
  "CORONA NOR",
  "CORONA SC",
  "CRUZEIRO REAL",
  "DIRHAM",
  "DOLAR AUST",
  "DOLAR CAN",
  "DOLAR HK",
  "DOLAR NZ",
  "DOLAR SIN",
  "DOLAR TAI",
  "DOLAR USA",
  "DRACMA",
  "ESCUDO",
  "EURO",
  "FLORIN",
  "FRANCO BEL",
  "FRANCO FR",
  "FRANCO SZ",
  "GUARANI",
  "LIBRA EST",
  "LIRA",
  "MARCO AL",
  "MARCO FIN",
  "NUEVO SOL",
  "OTRAS MONEDAS",
  "PESETA",
  "PESO",
  "PESO CL",
  "PESO COL",
  "PESO MEX",
  "PESO URUG",
  "RAND",
  "RENMINBI",
  "RUPIA",
  "SUCRE",
  "YEN"
]

// Código ISO 4217 con que se MUESTRA cada moneda. El valor que se guarda y
// que viaja en el <TpoMoneda> del DTE es SIEMPRE el nombre de la lista de
// arriba —es la enumeración TipMonType del XSD y el SII rechaza cualquier
// otra cosa—, así que esto no puede reemplazarlo: solo lo traduce al
// mostrarlo, porque "USD 1.200" se lee de una y "1.200 DOLAR USA" no.
//
// Las que no aparecen acá se muestran con su nombre del SII tal cual: son
// monedas históricas (ESCUDO, DRACMA, las anteriores al euro) o genéricas
// (OTRAS MONEDAS, PESO) que no tienen un ISO que no induzca a error.
const CODIGO_ISO_MONEDA: Record<string, string> = {
  'BOLIVAR': 'VES',
  'BOLIVIANO': 'BOB',
  'CORONA DIN': 'DKK',
  'CORONA NOR': 'NOK',
  'CORONA SC': 'SEK',
  'DIRHAM': 'AED',
  'DOLAR AUST': 'AUD',
  'DOLAR CAN': 'CAD',
  'DOLAR HK': 'HKD',
  'DOLAR NZ': 'NZD',
  'DOLAR SIN': 'SGD',
  'DOLAR TAI': 'TWD',
  'DOLAR USA': 'USD',
  'EURO': 'EUR',
  'FRANCO SZ': 'CHF',
  'GUARANI': 'PYG',
  'LIBRA EST': 'GBP',
  'NUEVO SOL': 'PEN',
  'PESO CL': 'CLP',
  'PESO COL': 'COP',
  'PESO MEX': 'MXN',
  'PESO URUG': 'UYU',
  'RAND': 'ZAR',
  'RENMINBI': 'CNY',
  'RUPIA': 'INR',
  'YEN': 'JPY'
}

export function codigoIsoMoneda(moneda: string): string {
  return CODIGO_ISO_MONEDA[moneda] ?? moneda
}

// <FmaPagExp> — Anexo 51-22 (solo las formas simples; los códigos 50-79 son
// combinaciones de pago anticipado con cobranza/crédito que no se ofrecen).
export const FORMAS_PAGO_EXPORTACION: CodigoAduana[] = [
  { value: 1, label: 'COB1 — Cobranza hasta 1 año' },
  { value: 2, label: 'COBRANZA — Cobranza más de 1 año' },
  { value: 11, label: 'ACRED — Acreditivo hasta 1 año' },
  { value: 12, label: 'CBOF — Crédito bancos/org. financieros más de 1 año' },
  { value: 21, label: 'SIN PAGO' },
  { value: 32, label: 'ANTICIPO — Pago anticipado a la fecha de embarque' }
]

// <IndServicio> — solo para facturas de exportación de servicios.
export const INDICADORES_SERVICIO_EXPORTACION: CodigoAduana[] = [
  { value: 3, label: 'Servicios calificados como exportación por Aduana' },
  { value: 4, label: 'Servicios de hotelería' },
  { value: 5, label: 'Servicio de transporte terrestre internacional' }
]

// <CodModVenta> — Anexo 51-26.
export const MODALIDADES_VENTA: CodigoAduana[] = [
  { value: 1, label: 'A firme' },
  { value: 2, label: 'Bajo condición' },
  { value: 3, label: 'En consignación libre' },
  { value: 4, label: 'En consignación con un mínimo a firme' },
  { value: 9, label: 'Sin pago' }
]

// <CodClauVenta> — Anexo 51-21.
export const CLAUSULAS_VENTA: CodigoAduana[] = [
  { value: 1, label: 'CIF — Costos, seguro y flete' },
  { value: 2, label: 'CFR — Costos y flete' },
  { value: 3, label: 'EXW — En fábrica' },
  { value: 4, label: 'FAS — Franco al costado del buque' },
  { value: 5, label: 'FOB — Franco a bordo' },
  { value: 6, label: 'S/CL — Sin cláusula de compraventa' },
  { value: 7, label: 'FCA — Franco transportista' },
  { value: 8, label: 'OTRA (CPT, CIP, DPU, DAP)' },
  { value: 9, label: 'DDP — Entregadas derechos pagados' }
]

// <CodViaTransp> — Anexo 51-13.
export const VIAS_TRANSPORTE: CodigoAduana[] = [
  { value: 1, label: 'Marítima, fluvial y lacustre' },
  { value: 4, label: 'Aéreo' },
  { value: 5, label: 'Postal' },
  { value: 6, label: 'Ferroviario' },
  { value: 7, label: 'Carretero / terrestre' },
  { value: 8, label: 'Oleoductos, gasoductos' },
  { value: 9, label: 'Tendido eléctrico' },
  { value: 10, label: 'Otra' },
  { value: 11, label: 'Courier / aéreo' }
]

// <CodUnidMedTara>/<CodUnidPesoBruto>/<CodUnidPesoNeto> — Anexo 51-24 (las
// unidades con código confirmado en el compendio; KN es el default de
// Aduana para las declaraciones).
export const UNIDADES_ADUANA: CodigoAduana[] = [
  { value: 3, label: 'MKWH — 1000 kilowatt hora' },
  { value: 5, label: 'KLT — Kilate' },
  { value: 6, label: 'KN — Kilogramo' },
  { value: 9, label: 'LT — Litro' },
  { value: 10, label: 'U — Piezas o ítems' },
  { value: 12, label: 'U (JGO) — Juegos o mazos' },
  { value: 13, label: 'MU — 1000 piezas' },
  { value: 14, label: 'MT — Metro' },
  { value: 15, label: 'MT2 — Metro cuadrado' },
  { value: 16, label: 'MT3 — Metro cúbico' },
  { value: 17, label: '2U — Par' }
]

// <CodTpoBultos> — Anexo 51-23.
export const TIPOS_BULTO: CodigoAduana[] = [
  { value: 1, label: "GRANEL SÓLIDO, PARTICULAS FINAS (POLVO)" },
  { value: 2, label: "GRANEL SÓLIDO, PARTICULAS GRANULARES (GRANOS)" },
  { value: 3, label: "GRANEL SÓLIDO, PARTICULAS GRANDES (NÓDULOS)" },
  { value: 4, label: "GRANEL LÍQUIDO" },
  { value: 5, label: "GRANEL GASEOSO" },
  { value: 10, label: "PIEZAS" },
  { value: 11, label: "TUBOS" },
  { value: 12, label: "CILINDRO" },
  { value: 13, label: "ROLLOS" },
  { value: 16, label: "BARRAS" },
  { value: 17, label: "LINGOTES" },
  { value: 18, label: "TRONCOS" },
  { value: 19, label: "BLOQUE" },
  { value: 20, label: "ROLLIZO" },
  { value: 21, label: "CAJON" },
  { value: 22, label: "CAJAS DE CARTÓN" },
  { value: 23, label: "FARDO" },
  { value: 24, label: "BAÚL" },
  { value: 25, label: "COFRE" },
  { value: 26, label: "ARMAZÓN" },
  { value: 27, label: "BANDEJA" },
  { value: 28, label: "CAJAS DE MADERA" },
  { value: 29, label: "CAJAS DE LATA" },
  { value: 31, label: "BOTELLA DE GAS" },
  { value: 32, label: "BOTELLA" },
  { value: 33, label: "JAULAS" },
  { value: 34, label: "BIDON" },
  { value: 35, label: "JABAS" },
  { value: 36, label: "CESTAS" },
  { value: 37, label: "BARRILETE" },
  { value: 38, label: "TONEL" },
  { value: 39, label: "PIPAS" },
  { value: 40, label: "CAJAS NO ESPECIFICADAS" },
  { value: 41, label: "JARRO" },
  { value: 42, label: "FRASCO" },
  { value: 43, label: "DAMAJUANA" },
  { value: 44, label: "BARRIL" },
  { value: 45, label: "TAMBOR" },
  { value: 46, label: "CUÑETES" },
  { value: 47, label: "TARROS" },
  { value: 51, label: "CUBO" },
  { value: 61, label: "PAQUETE" },
  { value: 62, label: "SACOS" },
  { value: 63, label: "MALETA" },
  { value: 64, label: "BOLSA" },
  { value: 65, label: "BALA" },
  { value: 66, label: "RED" },
  { value: 67, label: "SOBRES" },
  { value: 73, label: "CONTENEDOR DE 20 PIES DRY" },
  { value: 74, label: "CONTENEDOR DE 40 PIES DRY" },
  { value: 75, label: "CONTENEDOR REFRIGERADO 20 PIES" },
  { value: 76, label: "CONTENEDOR REFRIGERADO 40 PIES" },
  { value: 77, label: "ESTANQUE (no utilizar para contenedor Tank)" },
  { value: 78, label: "CONTENEDOR NO ESPECIFICADO (Open Top, Tank, Flat Rack, otros)" },
  { value: 80, label: "PALLETS" },
  { value: 81, label: "TABLERO" },
  { value: 82, label: "LAMINAS" },
  { value: 83, label: "CARRETE" },
  { value: 85, label: "AUTOMOTOR" },
  { value: 86, label: "ATAUD" },
  { value: 88, label: "MAQUINARIA" },
  { value: 89, label: "PLANCHAS" },
  { value: 90, label: "ATADOS" },
  { value: 91, label: "BOBINA" },
  { value: 93, label: "OTROS BULTOS NO ESPECIFICADOS" },
  { value: 98, label: "NO EXISTE BULTO" },
  { value: 99, label: "SIN EMBALAR" }
]

// <CodPtoEmbarque>/<CodPtoDesemb> — Anexo 51-11.
export const PUERTOS: CodigoAduana[] = [
  { value: 111, label: "MONTREAL" },
  { value: 112, label: "COSTA DEL PACÍFICO, OTROS NO ESPECIFICADOS" },
  { value: 113, label: "HALIFAX" },
  { value: 114, label: "VANCOUVER" },
  { value: 115, label: "SAINT JOHN" },
  { value: 116, label: "TORONTO" },
  { value: 117, label: "OTROS PUERTOS DE CANADÁ NO IDENTIFICADOS" },
  { value: 118, label: "BAYSIDE" },
  { value: 120, label: "PORT CARTIES" },
  { value: 121, label: "COSTA DEL ATLÁNTICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE MAINE Y KEY WEST" },
  { value: 122, label: "PUERTOS DEL GOLFO DE MÉXICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE KEY WEST Y BROWNSVILLE" },
  { value: 123, label: "COSTA DEL PACÍFICO, OTROS NO ESPECIFICADOS" },
  { value: 124, label: "QUEBEC" },
  { value: 125, label: "PRINCE RUPERT" },
  { value: 126, label: "HAMILTON" },
  { value: 131, label: "BOSTON" },
  { value: 132, label: "NEW HAVEN" },
  { value: 133, label: "BRIDGEPORT" },
  { value: 134, label: "NEW YORK" },
  { value: 135, label: "FILADELFIA" },
  { value: 136, label: "BALTIMORE" },
  { value: 137, label: "NORFOLK" },
  { value: 139, label: "CHARLESTON" },
  { value: 140, label: "SAVANAH" },
  { value: 141, label: "MIAMI" },
  { value: 142, label: "EVERGLADES" },
  { value: 143, label: "JACKSONVILLE" },
  { value: 145, label: "PALM BEACH" },
  { value: 146, label: "BATON ROUGE" },
  { value: 147, label: "COLUMBRES" },
  { value: 148, label: "PITTSBURGH" },
  { value: 149, label: "DULUTH" },
  { value: 150, label: "MILWAUKEE" },
  { value: 151, label: "TAMPA" },
  { value: 152, label: "PENSACOLA" },
  { value: 153, label: "MOBILE" },
  { value: 154, label: "NEW ORLEANS" },
  { value: 155, label: "PORT ARTHUR" },
  { value: 156, label: "GALVESTON" },
  { value: 157, label: "CORPUS CRISTI" },
  { value: 158, label: "BROWNSVILLE" },
  { value: 159, label: "HOUSTON" },
  { value: 160, label: "OAKLAND" },
  { value: 161, label: "STOCKTON" },
  { value: 171, label: "SEATTLE" },
  { value: 172, label: "PORTLAND" },
  { value: 173, label: "SAN FRANCISCO" },
  { value: 174, label: "LOS ANGELES" },
  { value: 175, label: "LONG BEACH" },
  { value: 176, label: "SAN DIEGO" },
  { value: 180, label: "OTROS PUERTOS DE ESTADOS UNIDOS NO ESPECIFICADOS" },
  { value: 190, label: "PUNTA CHUNGO" },
  { value: 199, label: "LOS VILOS" },
  { value: 204, label: "PATACHE" },
  { value: 205, label: "CALBUCO" },
  { value: 206, label: "MICHILLA" },
  { value: 207, label: "PUERTO ANGAMOS" },
  { value: 208, label: "POSEIDON" },
  { value: 209, label: "TRES PUENTES" },
  { value: 210, label: "OTROS PUERTOS DE MÉXICO NO ESPECIFICADOS" },
  { value: 211, label: "TAMPICO" },
  { value: 212, label: "COSTA DEL PACÍFICO, OTROS PUERTOS" },
  { value: 213, label: "VERACRUZ" },
  { value: 214, label: "COATZACOALCOS" },
  { value: 215, label: "GUAYMAS" },
  { value: 216, label: "MAZATLAN" },
  { value: 217, label: "MANZANILLO" },
  { value: 218, label: "ACAPULCO" },
  { value: 219, label: "GOLFO DE MÉXICO, OTROS NO ESPECIFICADOS" },
  { value: 220, label: "ALTAMIRA" },
  { value: 221, label: "CRISTOBAL" },
  { value: 222, label: "BALBOA" },
  { value: 223, label: "COLON" },
  { value: 224, label: "OTROS PUERTOS DE PANAMÁ NO ESPECIFICADOS" },
  { value: 225, label: "PASO GUANACO SONSO" },
  { value: 231, label: "OTROS PUERTOS DE COLOMBIA NO ESPECIFICADOS" },
  { value: 232, label: "BUENAVENTURA" },
  { value: 233, label: "BARRANQUILLA" },
  { value: 241, label: "OTROS PUERTOS DE ECUADOR NO ESPECIFICADOS" },
  { value: 242, label: "GUAYAQUIL" },
  { value: 251, label: "OTROS PUERTOS DE PERÚ NO ESPECIFICADOS" },
  { value: 252, label: "CALLAO" },
  { value: 253, label: "ILO" },
  { value: 254, label: "IQUITOS" },
  { value: 261, label: "OTROS PUERTOS DE ARGENTINA NO ESPECIFICADOS" },
  { value: 262, label: "BUENOS AIRES" },
  { value: 263, label: "NECOCHEA" },
  { value: 264, label: "MENDOZA" },
  { value: 265, label: "CÓRDOBA" },
  { value: 266, label: "BAHIA BLANCA" },
  { value: 267, label: "COMODORO RIVADAVIA" },
  { value: 268, label: "PUERTO MADRYN" },
  { value: 269, label: "MAR DEL PLATA" },
  { value: 270, label: "ROSARIO" },
  { value: 271, label: "OTROS PUERTOS DE URUGUAY NO ESPECIFICADOS" },
  { value: 272, label: "MONTEVIDEO" },
  { value: 281, label: "OTROS PUERTOS DE VENEZUELA NO ESPECIFICADOS" },
  { value: 282, label: "LA GUAIRA" },
  { value: 285, label: "MARACAIBO" },
  { value: 291, label: "OTROS PUERTOS DE BRASIL NO ESPECIFICADOS" },
  { value: 292, label: "SANTOS" },
  { value: 293, label: "RIO DE JANEIRO" },
  { value: 294, label: "RIO GRANDE DEL SUR" },
  { value: 295, label: "PARANAGUA" },
  { value: 296, label: "SAO PAULO" },
  { value: 297, label: "SALVADOR" },
  { value: 301, label: "OTROS PUERTOS DE LAS ANTILLAS HOLANDESAS NO ESPECIFICADOS" },
  { value: 302, label: "CURAZAO" },
  { value: 399, label: "OTROS PUERTOS DE AMÉRICA NO ESPECIFICADOS" },
  { value: 411, label: "SHANGAI" },
  { value: 412, label: "DAIREN" },
  { value: 413, label: "OTROS PUERTOS DE CHINA NO ESPECIFICADOS" },
  { value: 420, label: "OTROS PUERTOS DE COREA DEL NORTE NO ESPECIFICADOS" },
  { value: 421, label: "NAMPO" },
  { value: 422, label: "BUSAN" },
  { value: 423, label: "OTROS PUERTOS DE COREA DEL SUR NO ESPECIFICADOS" },
  { value: 431, label: "MANILA" },
  { value: 432, label: "OTROS PUERTOS DE FILIPINAS NO ESPECIFICADOS" },
  { value: 441, label: "OTROS PUERTOS DE JAPON NO ESPECIFICADOS" },
  { value: 442, label: "OSAKA" },
  { value: 443, label: "KOBE" },
  { value: 444, label: "YOKOHAMA" },
  { value: 445, label: "NAGOYA" },
  { value: 446, label: "SHIMIZUI" },
  { value: 447, label: "MOJI" },
  { value: 448, label: "YAWATA" },
  { value: 449, label: "FUKUYAMA" },
  { value: 451, label: "KAOHSIUNG" },
  { value: 452, label: "KEELUNG" },
  { value: 453, label: "OTROS PUERTOS DE TAIWAN NO ESPECIFICADOS" },
  { value: 461, label: "KARHG ISLAND" },
  { value: 462, label: "OTROS PUERTOS DE IRAN NO ESPECIFICADOS" },
  { value: 471, label: "CALCUTA" },
  { value: 472, label: "OTROS PUERTOS DE INDIA NO ESPECIFICADOS" },
  { value: 481, label: "CHALNA" },
  { value: 482, label: "OTROS PUERTOS DE BANGLADESH NO ESPECIFICADOS" },
  { value: 491, label: "OTROS PUERTOS DE SINGAPUR NO ESPECIFICADOS" },
  { value: 492, label: "HONG KONG" },
  { value: 499, label: "OTROS PUERTOS ASIÁTICOS NO ESPECIFICADOS" },
  { value: 511, label: "CONSTANZA" },
  { value: 512, label: "OTROS PUERTOS DE RUMANIA NO ESPECIFICADOS" },
  { value: 521, label: "VARNA" },
  { value: 522, label: "OTROS PUERTOS DE BULGARIA NO ESPECIFICADOS" },
  { value: 533, label: "BELGRADO" },
  { value: 534, label: "OTROS PUERTOS DE SERBIA NO ESPECIFICADOS" },
  { value: 535, label: "PODGORITSA" },
  { value: 536, label: "OTROS PUERTOS DE MONTENEGRO NO ESPECIFICADOS" },
  { value: 541, label: "OTROS PUERTOS DE ITALIA NO ESPECIFICADOS" },
  { value: 542, label: "GENOVA" },
  { value: 543, label: "LIORNA, LIVORNO" },
  { value: 544, label: "NAPOLES" },
  { value: 545, label: "SALERNO" },
  { value: 546, label: "AUGUSTA" },
  { value: 547, label: "SAVONA" },
  { value: 551, label: "OTROS PUERTOS DE FRANCIA NO ESPECIFICADOS" },
  { value: 552, label: "LA PALLICE" },
  { value: 553, label: "LE HAVRE" },
  { value: 554, label: "MARSELLA" },
  { value: 555, label: "BURDEOS" },
  { value: 556, label: "CALAIS" },
  { value: 557, label: "BREST" },
  { value: 558, label: "RUAN" },
  { value: 561, label: "OTROS PUERTOS DE ESPAÑA NO ESPECIFICADOS" },
  { value: 562, label: "CADIZ" },
  { value: 563, label: "BARCELONA" },
  { value: 564, label: "BILBAO" },
  { value: 565, label: "HUELVA" },
  { value: 566, label: "SEVILLA" },
  { value: 567, label: "TARRAGONA" },
  { value: 568, label: "ALGECIRAS" },
  { value: 569, label: "VALENCIA" },
  { value: 571, label: "LIVERPOOL" },
  { value: 572, label: "LONDRES" },
  { value: 573, label: "ROCHESTER" },
  { value: 574, label: "ETEN SALVERRY" },
  { value: 576, label: "OTROS PUERTOS DE INGLATERRA NO ESPECIFICADOS" },
  { value: 577, label: "DOVER" },
  { value: 578, label: "PLYMOUTH" },
  { value: 581, label: "HELSINSKI" },
  { value: 582, label: "OTROS PUERTOS DE FINLANDIA NO ESPECIFICADOS" },
  { value: 583, label: "HANKO" },
  { value: 584, label: "KEMI" },
  { value: 585, label: "KOKKOLA" },
  { value: 586, label: "KOTKA" },
  { value: 587, label: "OULO" },
  { value: 588, label: "PIETARSAARI" },
  { value: 589, label: "PORI" },
  { value: 591, label: "BREMEN" },
  { value: 592, label: "HAMBURGO" },
  { value: 593, label: "NUREMBERG" },
  { value: 594, label: "FRANKFURT" },
  { value: 595, label: "DUSSELDORF" },
  { value: 596, label: "OTROS PUERTOS DE ALEMANIA NO ESPECIFICADOS" },
  { value: 597, label: "CUXHAVEN" },
  { value: 598, label: "ROSTOCK" },
  { value: 599, label: "OLDENBURG" },
  { value: 601, label: "AMBERES" },
  { value: 602, label: "OTROS PUERTOS DE BÉLGICA NO ESPECIFICADOS" },
  { value: 603, label: "ZEEBRUGGE" },
  { value: 604, label: "GHENT" },
  { value: 605, label: "OOSTENDE" },
  { value: 611, label: "LISBOA" },
  { value: 612, label: "OTROS PUERTOS DE PORTUGAL NO ESPECIFICADOS" },
  { value: 613, label: "SETUBAL" },
  { value: 621, label: "AMSTERDAM" },
  { value: 622, label: "ROTTERDAM" },
  { value: 623, label: "OTROS PUERTOS DE PAÍSES BAJOS NO ESPECIFICADOS" },
  { value: 631, label: "GOTEMBURGO" },
  { value: 632, label: "OTROS PUERTOS DE SUECIA NO ESPECIFICADOS" },
  { value: 633, label: "MALMO" },
  { value: 634, label: "HELSIMBORG" },
  { value: 635, label: "KALMAR" },
  { value: 641, label: "AARHUS" },
  { value: 642, label: "COPENHAGEN" },
  { value: 643, label: "OTROS PUERTOS DE DINAMARCA NO ESPECIFICADOS" },
  { value: 644, label: "AALBORG" },
  { value: 645, label: "ODENSE" },
  { value: 651, label: "OSLO" },
  { value: 652, label: "OTROS PUERTOS DE NORUEGA NO ESPECIFICADOS" },
  { value: 653, label: "STAVANGER" },
  { value: 699, label: "OTROS PUERTOS DE EUROPA NO ESPECIFICADOS" },
  { value: 711, label: "DURBAM" },
  { value: 712, label: "CIUDAD DEL CABO" },
  { value: 713, label: "OTROS PUERTOS DE SUDÁFRICA NO ESPECIFICADOS" },
  { value: 714, label: "SALDANHA" },
  { value: 715, label: "PORT-ELIZABETH" },
  { value: 716, label: "MOSSEL-BAY" },
  { value: 717, label: "EAST-LONDON" },
  { value: 799, label: "OTROS PUERTOS DE ÁFRICA NO ESPECIFICADOS" },
  { value: 811, label: "SIDNEY" },
  { value: 812, label: "FREMANTLE" },
  { value: 813, label: "OTROS PUERTOS DE AUSTRALIA NO ESPECIFICADOS" },
  { value: 814, label: "ADELAIDA" },
  { value: 815, label: "DARWIN" },
  { value: 816, label: "GERALDTON" },
  { value: 817, label: "PUERTO CABO FROWARD" },
  { value: 818, label: "MUELLE HUACHIPATO" },
  { value: 819, label: "TERMINAL MARÍTIMO ESCUADRÓN" },
  { value: 820, label: "TERMINAL PORTUARIO TERQUIM" },
  { value: 821, label: "TERMINAL MUELLE MECANIZADO ESPERANZA" },
  { value: 822, label: "TERMINAL MARÍTIMO ENAEX" },
  { value: 823, label: "TERMINAL MARÍTIMO OXIQUIM" },
  { value: 824, label: "TERMINAL GRÁNELES DEL NORTE" },
  { value: 825, label: "AERÓDROMO LA ARAUCANÍA" },
  { value: 826, label: "ESTACIÓN DE MEDICIÓN RECINTO" },
  { value: 827, label: "TERMINAL GRANELES DEL NORTE" },
  { value: 828, label: "MUELLE INTERACID TRADING (CHILE) S.A." },
  { value: 829, label: "TERMINAL MARITIMO ABASTIBLE" },
  { value: 830, label: "TERMINAL MARITIMO ENAP" },
  { value: 831, label: "AERÓDROMO PICHOY" },
  { value: 899, label: "OTROS PUERTOS DE OCEANÍA NO ESPECIFICADOS" },
  { value: 900, label: "RANCHO DE NAVES Y AERONAVES DE TRANSPORTE INTERNACIONAL" },
  { value: 901, label: "ARICA" },
  { value: 902, label: "IQUIQUE" },
  { value: 903, label: "ANTOFAGASTA" },
  { value: 904, label: "COQUIMBO" },
  { value: 905, label: "VALPARAÍSO" },
  { value: 906, label: "SAN ANTONIO" },
  { value: 907, label: "TALCAHUANO" },
  { value: 908, label: "SAN VICENTE" },
  { value: 909, label: "LIRQUEN" },
  { value: 910, label: "PUERTO MONTT" },
  { value: 911, label: "CHACABUCO PUERTO AYSEN" },
  { value: 912, label: "PUNTA ARENAS" },
  { value: 913, label: "PATILLOS" },
  { value: 914, label: "TOCOPILLA" },
  { value: 915, label: "MEJILLONES" },
  { value: 916, label: "TALTAL" },
  { value: 917, label: "CHAÑARAL BARQUITO" },
  { value: 918, label: "CALDERA" },
  { value: 919, label: "CALDERILLA" },
  { value: 920, label: "HUASCO GUACOLDA" },
  { value: 921, label: "QUINTERO" },
  { value: 922, label: "JUAN FERNANDEZ" },
  { value: 923, label: "CONSTITUCION" },
  { value: 924, label: "TOME" },
  { value: 925, label: "PENCO" },
  { value: 926, label: "CORONEL" },
  { value: 927, label: "LOTA" },
  { value: 928, label: "LEBU" },
  { value: 929, label: "ISLA DE PASCUA" },
  { value: 930, label: "CORRAL" },
  { value: 931, label: "ANCUD" },
  { value: 932, label: "CASTRO" },
  { value: 933, label: "QUELLÓN" },
  { value: 934, label: "CHAITÉN" },
  { value: 935, label: "TORTEL" },
  { value: 936, label: "NATALES" },
  { value: 937, label: "GUARELLO" },
  { value: 938, label: "PUERTO ANDINO" },
  { value: 939, label: "PERCY" },
  { value: 940, label: "CLARENCIA" },
  { value: 941, label: "GREGORIO" },
  { value: 942, label: "CABO NEGRO" },
  { value: 943, label: "PUERTO WILLIAMS" },
  { value: 944, label: "TERRITORIO ANTÁRTICO CHILENO" },
  { value: 945, label: "AEROPUERTO CARRIEL SUR" },
  { value: 946, label: "GUAYACAN" },
  { value: 947, label: "PASO PEHUENCHE" },
  { value: 948, label: "VENTANAS" },
  { value: 949, label: "PINO HACHADO (LIUCURA)" },
  { value: 950, label: "CALETA COLOSO" },
  { value: 951, label: "AGUAS NEGRAS" },
  { value: 952, label: "ZONA FRANCA IQUIQUE" },
  { value: 953, label: "ZONA FRANCA PUNTA ARENAS" },
  { value: 954, label: "RÍO MAYER" },
  { value: 955, label: "RÍO MOSCO" },
  { value: 956, label: "VISVIRI" },
  { value: 957, label: "CHACALLUTA" },
  { value: 958, label: "CHUNGARÁ" },
  { value: 959, label: "COLCHANE" },
  { value: 960, label: "ABRA DE NAPA" },
  { value: 961, label: "OLLAGUE" },
  { value: 962, label: "SAN PEDRO DE ATACAMA" },
  { value: 963, label: "SOCOMPA" },
  { value: 964, label: "SAN FRANCISCO" },
  { value: 965, label: "LOS LIBERTADORES" },
  { value: 966, label: "MAHUIL MALAL" },
  { value: 967, label: "CARDENAL SAMORE" },
  { value: 968, label: "PEREZ ROSALES" },
  { value: 969, label: "FUTALEUFU" },
  { value: 970, label: "PALENA CARRENLEUFU" },
  { value: 971, label: "PANGUIPULLI" },
  { value: 972, label: "HUAHUM" },
  { value: 973, label: "LAGO VERDE" },
  { value: 974, label: "APPELEG" },
  { value: 975, label: "PAMPA ALTA" },
  { value: 976, label: "HUEMULES" },
  { value: 977, label: "CHILE CHICO" },
  { value: 978, label: "BAKER" },
  { value: 979, label: "DOROTEA" },
  { value: 980, label: "CASAS VIEJAS" },
  { value: 981, label: "MONTE AYMOND" },
  { value: 982, label: "SAN SEBASTIAN" },
  { value: 983, label: "COYHAIQUE ALTO" },
  { value: 984, label: "TRIANA" },
  { value: 985, label: "IBAÑEZ PALAVICINI" },
  { value: 986, label: "VILLA O'HIGGINS" },
  { value: 987, label: "AEROP. CHACALLUTA" },
  { value: 988, label: "AEROP. DIEGO ARACENA" },
  { value: 989, label: "AEROP. CERRO MORENO" },
  { value: 990, label: "AEROP. EL TEPUAL" },
  { value: 991, label: "AEROP. C.I. DEL CAMPO" },
  { value: 992, label: "AEROP. A.M. BENITEZ" },
  { value: 993, label: "AERÓDROMO EL LOA" },
  { value: 994, label: "ARICA-TACNA" },
  { value: 995, label: "ARICA-LA PAZ" },
  { value: 997, label: "OTROS PUERTOS CHILENOS" },
  { value: 998, label: "PASO JAMA" },
  { value: 999, label: "GNL MEJILLONES" }
]

// <CodPaisRecep>/<CodPaisDestin> y la nacionalidad del receptor extranjero —
// Anexo 51-9.
export const PAISES: CodigoAduana[] = [
  { value: 101, label: "SENEGAL" },
  { value: 102, label: "GAMBIA" },
  { value: 103, label: "GUINEA - BISSAU" },
  { value: 104, label: "GUINEA" },
  { value: 105, label: "SIERRA LEONA" },
  { value: 106, label: "LIBERIA" },
  { value: 107, label: "COSTA DE MARFIL" },
  { value: 108, label: "GHANA" },
  { value: 109, label: "TOGO" },
  { value: 111, label: "NIGERIA" },
  { value: 112, label: "SUDAFRICA" },
  { value: 113, label: "BOTSWANA" },
  { value: 114, label: "LESOTHO" },
  { value: 115, label: "MALAWI" },
  { value: 116, label: "ZIMBABWE" },
  { value: 117, label: "ZAMBIA" },
  { value: 118, label: "COMORAS" },
  { value: 119, label: "MAURICIO" },
  { value: 120, label: "MADAGASCAR" },
  { value: 121, label: "MOZAMBIQUE" },
  { value: 122, label: "SWAZILANDIA" },
  { value: 123, label: "SUDAN" },
  { value: 124, label: "EGIPTO" },
  { value: 125, label: "LIBIA" },
  { value: 126, label: "TUNEZ" },
  { value: 127, label: "ARGELIA" },
  { value: 128, label: "MARRUECOS" },
  { value: 129, label: "CABO VERDE" },
  { value: 130, label: "CHAD" },
  { value: 131, label: "NIGER" },
  { value: 133, label: "MALI" },
  { value: 134, label: "MAURITANIA" },
  { value: 135, label: "TANZANIA" },
  { value: 136, label: "UGANDA" },
  { value: 137, label: "KENIA" },
  { value: 138, label: "SOMALIA" },
  { value: 139, label: "ETIOPIA" },
  { value: 140, label: "ANGOLA" },
  { value: 141, label: "BURUNDI" },
  { value: 142, label: "RWANDA" },
  { value: 143, label: "REPUBLICA DEMOCRATICA DEL CONGO" },
  { value: 144, label: "CONGO" },
  { value: 145, label: "GABON" },
  { value: 146, label: "SAO TOME Y PRINCIPE" },
  { value: 147, label: "GUINEA ECUATORIAL" },
  { value: 149, label: "CAMERUN" },
  { value: 150, label: "BENIN" },
  { value: 151, label: "TERRITORIO BRITÁNICO EN AFRICA" },
  { value: 152, label: "TERRITORIO ESPAÑOL EN AFRICA" },
  { value: 153, label: "TERRITORIO FRANCES EN AFRICA" },
  { value: 155, label: "DJIBOUTI" },
  { value: 156, label: "SEYCHELLES" },
  { value: 159, label: "NAMIBIA" },
  { value: 161, label: "BURKINA FASO" },
  { value: 163, label: "ERITREA" },
  { value: 164, label: "ISLAS MARSHALL" },
  { value: 165, label: "SAHARA OCCIDENTAL" },
  { value: 201, label: "VENEZUELA" },
  { value: 202, label: "COLOMBIA" },
  { value: 203, label: "TRINIDAD Y TOBAGO" },
  { value: 204, label: "BARBADOS" },
  { value: 205, label: "JAMAICA" },
  { value: 207, label: "BAHAMAS" },
  { value: 208, label: "HAITI" },
  { value: 209, label: "CUBA" },
  { value: 210, label: "PANAMA" },
  { value: 211, label: "COSTA RICA" },
  { value: 212, label: "NICARAGUA" },
  { value: 213, label: "EL SALVADOR" },
  { value: 214, label: "HONDURAS" },
  { value: 215, label: "GUATEMALA" },
  { value: 216, label: "MEXICO" },
  { value: 217, label: "GUYANA" },
  { value: 218, label: "ECUADOR" },
  { value: 219, label: "PERU" },
  { value: 220, label: "BRASIL" },
  { value: 221, label: "BOLIVIA" },
  { value: 222, label: "PARAGUAY" },
  { value: 223, label: "URUGUAY" },
  { value: 224, label: "ARGENTINA" },
  { value: 225, label: "ESTADOS UNIDOS DE AMÉRICA" },
  { value: 226, label: "CANADA" },
  { value: 227, label: "TERRITORIO BRITÁNICO EN AMERICA" },
  { value: 228, label: "TERRITORIO FRANCES EN AMERICA" },
  { value: 229, label: "TERRITORIO HOLANDES EN AMERICA" },
  { value: 230, label: "TERRITORIO DE DINAMARCA" },
  { value: 231, label: "DOMINICA" },
  { value: 232, label: "GRANADA" },
  { value: 233, label: "SANTA LUCIA (ISLAS OCCIDENTALES)" },
  { value: 234, label: "SAN VICENTE Y LAS GRANADINAS" },
  { value: 235, label: "SURINAM" },
  { value: 236, label: "BELICE" },
  { value: 240, label: "ANTIGUA Y BARBUDA" },
  { value: 241, label: "SAINT KITTS & NEVIS" },
  { value: 242, label: "ANGUILA" },
  { value: 243, label: "ARUBA" },
  { value: 244, label: "BERMUDAS" },
  { value: 245, label: "ISLAS VIRGENES BRITANICAS" },
  { value: 246, label: "ISLAS CAYMAN" },
  { value: 247, label: "ANTILLAS NEERLANDESAS" },
  { value: 248, label: "TURCAS Y CAICOS" },
  { value: 249, label: "ISLAS VIRGENES (ESTADOS UNIDOS DE AMERICA)" },
  { value: 250, label: "MARTINICA" },
  { value: 251, label: "PUERTO RICO" },
  { value: 252, label: "MONSERRAT" },
  { value: 253, label: "GROENLANDIA" },
  { value: 301, label: "JORDANIA" },
  { value: 302, label: "ARABIA SAUDITA" },
  { value: 303, label: "KUWAIT" },
  { value: 304, label: "OMAN" },
  { value: 305, label: "CHIPRE" },
  { value: 306, label: "ISRAEL" },
  { value: 307, label: "IRAK" },
  { value: 308, label: "AFGHANISTAN" },
  { value: 309, label: "IRAN" },
  { value: 310, label: "SIRIA" },
  { value: 311, label: "LIBANO" },
  { value: 312, label: "QATAR" },
  { value: 313, label: "BAHREIN" },
  { value: 314, label: "SRI LANKA" },
  { value: 315, label: "CAMBODIA" },
  { value: 316, label: "LAOS" },
  { value: 317, label: "INDIA" },
  { value: 318, label: "BUTAN" },
  { value: 319, label: "THAILANDIA" },
  { value: 320, label: "NEPAL" },
  { value: 321, label: "BANGLADESH" },
  { value: 324, label: "PAKISTAN" },
  { value: 325, label: "VIETNAM" },
  { value: 326, label: "MYANMAR (EX BIRMANIA)" },
  { value: 327, label: "ISLAS MALDIVAS" },
  { value: 328, label: "INDONESIA" },
  { value: 329, label: "MALASIA" },
  { value: 330, label: "TAIWAN (FORMOSA)" },
  { value: 331, label: "JAPON" },
  { value: 332, label: "SINGAPUR" },
  { value: 333, label: "COREA DEL SUR" },
  { value: 334, label: "COREA DEL NORTE" },
  { value: 335, label: "FILIPINAS" },
  { value: 336, label: "CHINA" },
  { value: 337, label: "MONGOLIA" },
  { value: 341, label: "EMIRATOS ARABES UNIDOS" },
  { value: 342, label: "HONG KONG - REGIÓN ADMINISTRATIVA ESPECIAL DE CHINA" },
  { value: 343, label: "TERRITORIO PORTUGUES EN ASIA" },
  { value: 344, label: "BRUNEI" },
  { value: 345, label: "MACAO" },
  { value: 346, label: "REPUBLICA DE YEMEN" },
  { value: 401, label: "FIJI" },
  { value: 402, label: "NAURU" },
  { value: 403, label: "ISLAS TONGA" },
  { value: 404, label: "SAMOA OCCIDENTAL" },
  { value: 405, label: "NUEVA ZELANDIA" },
  { value: 406, label: "AUSTRALIA" },
  { value: 407, label: "TERRITORIO BRITÁNICO EN OCEANIA Y EL PACIFICO" },
  { value: 408, label: "TERRITORIO FRANCES EN OCEANIA Y EL PACIFICO" },
  { value: 409, label: "TERRITORIO NORTEAMERICANO EN OCEANIA Y EL PACIFICO" },
  { value: 415, label: "VANUATU" },
  { value: 416, label: "KIRIBATI" },
  { value: 417, label: "MICRONESIA" },
  { value: 418, label: "ISLAS SALOMON" },
  { value: 419, label: "TUVALU" },
  { value: 420, label: "BELAU" },
  { value: 421, label: "NIUE" },
  { value: 422, label: "POLINESIA FRANCESA" },
  { value: 423, label: "NUEVA CALEDONIA" },
  { value: 424, label: "ISLAS MARIANAS DEL NORTE" },
  { value: 425, label: "GUAM" },
  { value: 426, label: "TIMOR ORIENTAL" },
  { value: 427, label: "ISLAS COOK" },
  { value: 501, label: "PORTUGAL" },
  { value: 504, label: "ITALIA" },
  { value: 505, label: "FRANCIA" },
  { value: 506, label: "IRLANDA" },
  { value: 507, label: "DINAMARCA" },
  { value: 508, label: "SUIZA" },
  { value: 509, label: "AUSTRIA" },
  { value: 510, label: "REINO UNIDO" },
  { value: 511, label: "SUECIA" },
  { value: 512, label: "FINLANDIA" },
  { value: 513, label: "NORUEGA" },
  { value: 514, label: "BELGICA" },
  { value: 515, label: "PAÍSES BAJOS" },
  { value: 516, label: "ISLANDIA" },
  { value: 517, label: "ESPAÑA" },
  { value: 518, label: "ALBANIA" },
  { value: 519, label: "RUMANIA" },
  { value: 520, label: "GRECIA" },
  { value: 522, label: "TURQUIA" },
  { value: 523, label: "MALTA" },
  { value: 524, label: "SANTA SEDE" },
  { value: 525, label: "ANDORRA" },
  { value: 527, label: "BULGARIA" },
  { value: 528, label: "POLONIA" },
  { value: 530, label: "HUNGRIA" },
  { value: 532, label: "LUXEMBURGO" },
  { value: 534, label: "LIECHTENSTEIN" },
  { value: 535, label: "MONACO" },
  { value: 536, label: "SAN MARINO" },
  { value: 540, label: "ARMENIA" },
  { value: 541, label: "AZERBAIJAN" },
  { value: 542, label: "BELARUS" },
  { value: 543, label: "BOSNIA Y HERZEGOVINA" },
  { value: 544, label: "REPUBLICA CHECA (D)" },
  { value: 547, label: "CROACIA" },
  { value: 548, label: "ESLOVENIA" },
  { value: 549, label: "ESTONIA" },
  { value: 550, label: "GEORGIA" },
  { value: 551, label: "KASAJSTAN" },
  { value: 552, label: "KIRGISTAN" },
  { value: 553, label: "LETONIA" },
  { value: 554, label: "LITUANIA" },
  { value: 555, label: "MACEDONIA" },
  { value: 556, label: "MOLDOVA" },
  { value: 557, label: "TADJIKISTAN" },
  { value: 558, label: "TURKMENISTAN" },
  { value: 559, label: "UCRANIA" },
  { value: 560, label: "UZBEKISTAN" },
  { value: 562, label: "RUSIA (B)" },
  { value: 563, label: "ALEMANIA" },
  { value: 565, label: "GIBRALTAR" },
  { value: 566, label: "GUERNSEY" },
  { value: 567, label: "ISLAS DE MAN" },
  { value: 568, label: "JERSEY" },
  { value: 901, label: "Combustibles y lubricantes destinados al consumo de naves y aeronaves extranjeras y de revistas con el mismo objeto" },
  { value: 902, label: "Aprovisionamiento (\"Rancho\") de naves y aeronaves extranjeras y de maderas para estibar mercancías cargadas en puertos chilenos" },
  { value: 904, label: "Orígenes o Destinaciones no precisadas por razones comerciales o militares" },
  { value: 905, label: "Zona Franca Iquique" },
  { value: 906, label: "Depósito Franco" },
  { value: 907, label: "Zona Franca Punta Arenas" },
  { value: 910, label: "Zona Franca Arica, Zona Industrial" },
  { value: 997, label: "CHILE" },
  { value: 999, label: "Otros (País Desconocido)" }
]
